### ISSUE TITLE
Mod still working but throwing an error to the Smapi window

### ISSUE THREAD

**Issue by the-aterna-10** [Bpendragon/GreenhouseSprinklers#10]
The mod kept throwing a large red error to my SMAPI console window and didn't know if you knew about it or not
It keeps saying the the mod fails in the gameloop.saving event
not sure if this is a problem for my computer or if its for the mod in general

Here is a pastebin link for my SMAPI log: [link](https://pastebin.com/HsDdRuze)

**Comment by Bpendragon** [comment]
A few people have reported this on Nexus as well, I'm tring to do an investigation but have never managed to replicate the problem myself.

**Comment by Bpendragon** [comment]
Fixed in #12
